In [1]:
import cv2
import numpy as np

# Baca gambar dalam grayscale
img_gray = cv2.imread("/Users/anggun/Downloads/SKRIPSI ANGGUN/ANGGUN/2. Data Baru CLAHE/CLAHE/Corrugation/1_3_TURI_Corrugation_Foto.jpeg", cv2.IMREAD_GRAYSCALE)

# Ukuran gambar
print("Ukuran gambar:", img_gray.shape)

# Tampilkan sebagian matriks (misalnya 10x10 pertama, biar tidak kepanjangan)
print("Contoh matriks piksel 10x10 pertama:\n", img_gray[:4, :4])

# Jika ingin seluruh matriks
# WARNING: bisa sangat panjang kalau gambarnya besar
# print("Matriks penuh:\n", img_gray)


Ukuran gambar: (299, 299)
Contoh matriks piksel 10x10 pertama:
 [[149  89 221 242]
 [156 104 225 243]
 [135  69 126 130]
 [ 67  94 119  44]]
